// _tools/badge/main.go
//
// Generates a coverage badge SVG by fetching it from shields.io.
//
// Usage (called automatically by `make coverage`):
//
//	go run ./_tools/badge -in=.public/coverage.out -out=.public/coverage.svg
//
// Flags:
//
//	-in    path to the coverage profile generated by `go test -coverprofile`
//	-out   destination path for the SVG badge
//	-label left-hand label text shown on the badge (default: "coverage")
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// totalCoverage runs `go tool cover -func` on profilePath and returns the
// total coverage as a display string (e.g. "84.2") and a float64.
func totalCoverage(profilePath string) (string, float64, error) {
	cmd := exec.Command("go", "tool", "cover", "-func="+profilePath)
	b, err := cmd.CombinedOutput()
	if err != nil {
		return "", 0, fmt.Errorf("go tool cover failed: %v\n%s", err, string(b))
	}

	lines := strings.Split(strings.TrimSpace(string(b)), "\n")
	if len(lines) == 0 {
		return "", 0, fmt.Errorf("empty output from go tool cover")
	}

	// The last line is always the total:
	//   total:   (statements)   84.2%
	last := lines[len(lines)-1]
	fields := strings.Fields(last)
	if len(fields) == 0 {
		return "", 0, fmt.Errorf("unexpected final line: %q", last)
	}

	raw := strings.TrimSuffix(fields[len(fields)-1], "%")
	value, err := strconv.ParseFloat(raw, 64)
	if err != nil {
		return "", 0, fmt.Errorf("invalid percentage %q: %w", raw, err)
	}

	return raw, value, nil
}

// badgeColor maps a coverage percentage to a shields.io named colour.
// Thresholds match the convention used across the Go ecosystem.
func badgeColor(p float64) string {
	switch {
	case p >= 90:
		return "brightgreen"
	case p >= 80:
		return "green"
	case p >= 70:
		return "yellowgreen"
	case p >= 60:
		return "yellow"
	case p >= 50:
		return "orange"
	default:
		return "red"
	}
}

// download fetches url via HTTP GET and writes the response body to dest.
func download(url, dest string) error {
	fmt.Println("Downloading", url)

	resp, err := http.Get(url) //nolint:noctx
	if err != nil {
		return fmt.Errorf("http get: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("http %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}

	f, err := os.Create(dest)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	if _, err = io.Copy(f, resp.Body); err != nil {
		return fmt.Errorf("write file: %w", err)
	}
	return nil
}

// escape makes a string safe for use in a shields.io URL segment.
// shields.io uses `-` as separator and `_` for spaces, so both must
// be doubled to be treated as literals.
func escape(s string) string {
	return strings.NewReplacer("-", "--", "_", "__", " ", "_").Replace(s)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err.Error())
	os.Exit(1)
}

func main() {
	in := flag.String("in", ".public/coverage.out", "input coverage profile path")
	out := flag.String("out", ".public/coverage.svg", "output badge SVG path")
	label := flag.String("label", "coverage", "left-hand label on the badge")
	flag.Parse()

	pctText, pctValue, err := totalCoverage(*in)
	if err != nil {
		fail(err)
	}

	color := badgeColor(pctValue)

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail(fmt.Errorf("mkdir: %w", err))
	}

	// shields.io flat badge URL format:
	// https://img.shields.io/badge/<label>-<message>-<color>.svg
	url := fmt.Sprintf(
		"https://img.shields.io/badge/%s-%s%%25-%s.svg",
		escape(*label),
		escape(pctText),
		escape(color),
	)

	if err := download(url, *out); err != nil {
		fail(err)
	}

	fmt.Printf("Coverage: %s%%  →  %s\n", pctText, *out)
}
